services:
  backend:
    build: ./fcv-be
    command: npm run start:dev
    ports:
      - "3000:3000"
    networks:
      - fcv-network
    depends_on:
      - mongo
  
  frontend:
    build: ./fcv-fe
    command: npm run dev
    ports:
      - "3001:3000"
    networks:
      - fcv-network
    depends_on:
      - backend

  mongo:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - fcv-network
    volumes:
      - fcv-db:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - fcv-network

networks:
  fcv-network:
    driver: bridge

volumes:
  fcv-db:
